using System.Text.RegularExpressions;

namespace ScientificResearchAssistant.Api.Workspace;

// ============================================================
//  WorkspaceService (File-SSoT)
//
//  Responsibilities:
//  - Resolve and create deterministic workspace directories:
//      workspace/sessions/{sessionId}/...
//  - Enforce path safety (within-root) to avoid traversal bugs.
//  - Provide bounded scanning for UI snapshots (counts + metadata only).
//
//  Notes:
//  - This is NOT agent state; it's an infrastructure helper for file-backed collaboration.
// ============================================================

public sealed class WorkspaceService
{
    // Keep it simple and safe: session ids are generated by server, but validate anyway.
    private static readonly Regex SafeId = new(@"^[a-zA-Z0-9_-]{6,64}$", RegexOptions.Compiled);
    private const int MaxScanFiles = 5000;
    private const int MaxRecentScanFiles = 2000;

    private readonly IHostEnvironment _env;
    private readonly ILogger<WorkspaceService> _logger;

    public WorkspaceService(IHostEnvironment env, ILogger<WorkspaceService> logger)
    {
        _env = env ?? throw new ArgumentNullException(nameof(env));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    public WorkspacePaths EnsureSessionWorkspace(string sessionId)
    {
        sessionId = NormalizeId(sessionId, nameof(sessionId));

        var systemRoot = ResolveSystemRoot();
        var workspaceRoot = Path.Combine(systemRoot, "workspace");
        var sessionsRoot = Path.Combine(workspaceRoot, "sessions");
        var sessionRoot = Path.Combine(sessionsRoot, sessionId);

        // Safety: ensure resolved paths cannot escape system root.
        EnsureWithinRoot(systemRoot, workspaceRoot);
        EnsureWithinRoot(systemRoot, sessionsRoot);
        EnsureWithinRoot(systemRoot, sessionRoot);

        var paperDir = Path.Combine(sessionRoot, "paper");
        var factsProposedDir = Path.Combine(sessionRoot, "facts_proposed");
        var decisionsDir = Path.Combine(sessionRoot, "decisions");
        var mailboxDir = Path.Combine(sessionRoot, "mailbox");
        var runsDir = Path.Combine(sessionRoot, "runs");
        var artifactsDir = Path.Combine(sessionRoot, "artifacts");
        var tmpDir = Path.Combine(sessionRoot, "tmp");

        // Mailbox internal folders (created lazily per agent, but ensure shared ones).
        var deadDir = Path.Combine(mailboxDir, "_dead");

        // Create directories (idempotent).
        Directory.CreateDirectory(paperDir);
        Directory.CreateDirectory(factsProposedDir);
        Directory.CreateDirectory(decisionsDir);
        Directory.CreateDirectory(mailboxDir);
        Directory.CreateDirectory(deadDir);
        Directory.CreateDirectory(runsDir);
        Directory.CreateDirectory(artifactsDir);
        Directory.CreateDirectory(tmpDir);

        return new WorkspacePaths
        {
            SystemRoot = systemRoot,
            WorkspaceRoot = workspaceRoot,
            SessionsRoot = sessionsRoot,
            SessionId = sessionId,
            SessionRoot = sessionRoot,
            PaperDir = paperDir,
            PaperOutlinePath = Path.Combine(paperDir, "outline.md"),
            PaperDraftPath = Path.Combine(paperDir, "draft.md"),
            FactsProposedDir = factsProposedDir,
            DecisionsDir = decisionsDir,
            MailboxDir = mailboxDir,
            MailboxDeadDir = deadDir,
            RunsDir = runsDir,
            ArtifactsDir = artifactsDir,
            TmpDir = tmpDir,
            FactsDir = Path.Combine(systemRoot, "facts"),
            SourcesDir = Path.Combine(systemRoot, "sources") // optional; may not exist
        };
    }

    public WorkspaceScanResult ScanWorkspace(string sessionId)
    {
        var ws = EnsureSessionWorkspace(sessionId);

        // Bounded scan: count files only, no content reads.
        var factsCount = CountFilesSafe(ws.FactsDir);
        var sourcesCount = CountFilesSafe(ws.SourcesDir); // ok if missing
        var proposedCount = CountFilesSafe(ws.FactsProposedDir);

        // For UI: list a small set of newest items (paths only).
        var proposedTop = ListRecentFilesSafe(ws.FactsProposedDir, max: 20)
            .Select(p => NormalizeRelative(Path.GetRelativePath(ws.SessionRoot, p)))
            .ToList();

        return new WorkspaceScanResult
        {
            SessionId = ws.SessionId,
            FactsCount = factsCount,
            SourcesCount = sourcesCount,
            FactsProposedCount = proposedCount,
            FactsProposedRecent = proposedTop
        };
    }

    // ============================================================
    //  Path helpers
    // ============================================================

    private string ResolveSystemRoot()
    {
        // contentRoot: scientific-research-assistant/src/ScientificResearchAssistant.Api
        var contentRoot = _env.ContentRootPath;
        return Path.GetFullPath(Path.Combine(contentRoot, "..", ".."));
    }

    private static string NormalizeId(string id, string argName)
    {
        id = (id ?? string.Empty).Trim();
        if (!SafeId.IsMatch(id))
            throw new ArgumentException("invalid id format", argName);
        return id;
    }

    private static void EnsureWithinRoot(string root, string candidate)
    {
        root = Path.GetFullPath(root);
        candidate = Path.GetFullPath(candidate);

        if (!candidate.StartsWith(root + Path.DirectorySeparatorChar, StringComparison.Ordinal)
            && !string.Equals(candidate, root, StringComparison.Ordinal))
        {
            throw new InvalidOperationException($"path escapes root: {candidate}");
        }
    }

    private static int CountFilesSafe(string dir)
    {
        try
        {
            if (!Directory.Exists(dir))
                return 0;

            // Bounded scan: stop after MaxScanFiles to avoid pathological trees.
            var count = 0;
            foreach (var p in Directory.EnumerateFiles(dir, "*", SearchOption.AllDirectories))
            {
                if (!IsAllowedDoc(p)) continue;
                count++;
                if (count >= MaxScanFiles) break;
            }

            return count;
        }
        catch
        {
            return 0;
        }
    }

    private static List<string> ListRecentFilesSafe(string dir, int max)
    {
        try
        {
            if (!Directory.Exists(dir))
                return [];

            max = Math.Clamp(max, 0, 200);
            if (max == 0)
                return [];

            var candidates = Directory
                .EnumerateFiles(dir, "*", SearchOption.AllDirectories)
                .Where(IsAllowedDoc)
                .Take(MaxRecentScanFiles)
                .Select(p => new FileInfo(p))
                .OrderByDescending(fi => fi.LastWriteTimeUtc)
                .Take(max)
                .Select(fi => fi.FullName)
                .ToList();

            return candidates;
        }
        catch
        {
            return [];
        }
    }

    private static bool IsAllowedDoc(string path)
    {
        var ext = Path.GetExtension(path);
        return ext.Equals(".md", StringComparison.OrdinalIgnoreCase)
               || ext.Equals(".txt", StringComparison.OrdinalIgnoreCase)
               || ext.Equals(".json", StringComparison.OrdinalIgnoreCase);
    }

    private static string NormalizeRelative(string s)
    {
        return (s ?? string.Empty).Replace('\\', '/').Trim('/');
    }
}

public sealed record WorkspacePaths
{
    public required string SystemRoot { get; init; }
    public required string WorkspaceRoot { get; init; }
    public required string SessionsRoot { get; init; }

    public required string SessionId { get; init; }
    public required string SessionRoot { get; init; }

    public required string PaperDir { get; init; }
    public required string PaperOutlinePath { get; init; }
    public required string PaperDraftPath { get; init; }

    public required string FactsProposedDir { get; init; }
    public required string DecisionsDir { get; init; }

    public required string MailboxDir { get; init; }
    public required string MailboxDeadDir { get; init; }

    public required string RunsDir { get; init; }
    public required string ArtifactsDir { get; init; }
    public required string TmpDir { get; init; }

    public required string FactsDir { get; init; }
    public required string SourcesDir { get; init; }
}

public sealed record WorkspaceScanResult
{
    public required string SessionId { get; init; }

    public int FactsCount { get; init; }
    public int FactsProposedCount { get; init; }
    public int SourcesCount { get; init; }

    public List<string> FactsProposedRecent { get; init; } = new();
}


