import { create, fromJsonString, toJsonString } from "@bufbuild/protobuf";

// Generated Protobuf schemas (from `novel/protos/*.proto`)
// NOTE: `src/gen` is generated by `npm run proto:gen`.
import type { ProjectRootInfo, SidecarEvent } from "@/gen/novel_sidecar_pb";
import {
  ProjectRootInfoSchema,
  SetProjectRootRequestSchema,
  SetProjectRootResponseSchema,
  SidecarEventSchema,
} from "@/gen/novel_sidecar_pb";

// ============================================================
//  Sidecar Client (HTTP + SSE, Protobuf JSON)
//
//  Contract:
//  - GET  /api/novel/project-root -> ProjectRootInfo (protobuf json)
//  - POST /api/novel/project-root -> SetProjectRootRequest/Response (protobuf json)
//  - GET  /api/novel/events       -> SSE stream of SidecarEvent (protobuf json)
// ============================================================

export type SidecarConnectionState = "idle" | "connecting" | "connected" | "error";

export function defaultSidecarUrl(): string {
  const env = (import.meta as any).env?.VITE_NOVEL_SIDECAR_URL as string | undefined;
  return env?.trim() ? env.trim() : "http://127.0.0.1:5000";
}

export function normalizeBaseUrl(baseUrl: string): string {
  let s = (baseUrl ?? "").trim();
  if (!s) return defaultSidecarUrl();
  s = s.replace(/\/+$/g, "");
  return s;
}

export async function getProjectRootInfo(baseUrl: string, ct?: AbortSignal): Promise<ProjectRootInfo> {
  const url = `${normalizeBaseUrl(baseUrl)}/api/novel/project-root`;
  const res = await fetch(url, { signal: ct });
  if (!res.ok) {
    throw new Error(`GET ${url} failed: ${res.status} ${res.statusText}`);
  }
  const json = await res.text();
  return fromJsonString(ProjectRootInfoSchema, json);
}

export async function setProjectRoot(baseUrl: string, projectRoot: string): Promise<ProjectRootInfo> {
  const url = `${normalizeBaseUrl(baseUrl)}/api/novel/project-root`;
  const req = create(SetProjectRootRequestSchema, { projectRoot });
  const body = toJsonString(SetProjectRootRequestSchema, req);

  const res = await fetch(url, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body,
  });

  if (!res.ok) {
    throw new Error(`POST ${url} failed: ${res.status} ${res.statusText}`);
  }

  const json = await res.text();
  const msg = fromJsonString(SetProjectRootResponseSchema, json) as any;
  // proto3 message field may be omitted in JSON; keep it defensive.
  if (!msg?.info) {
    return create(ProjectRootInfoSchema);
  }
  return msg.info as ProjectRootInfo;
}

export function connectSidecarEvents(args: {
  baseUrl: string;
  onEvent: (evt: SidecarEvent) => void;
  onState?: (state: SidecarConnectionState, error?: string) => void;
}): () => void {
  const baseUrl = normalizeBaseUrl(args.baseUrl);
  const url = `${baseUrl}/api/novel/events`;

  args.onState?.("connecting");

  const es = new EventSource(url);

  const onOpen = () => args.onState?.("connected");
  const onError = () => args.onState?.("error", `SSE error: ${url}`);
  const onEvt = (e: MessageEvent) => {
    try {
      const evt = fromJsonString(SidecarEventSchema, String(e.data));
      args.onEvent(evt);
    } catch (err: any) {
      args.onState?.("error", `SSE decode failed: ${err?.message ?? String(err)}`);
    }
  };

  es.addEventListener("open", onOpen as any);
  es.addEventListener("error", onError as any);
  es.addEventListener("sidecar_event", onEvt as any);

  return () => {
    es.removeEventListener("open", onOpen as any);
    es.removeEventListener("error", onError as any);
    es.removeEventListener("sidecar_event", onEvt as any);
    es.close();
  };
}


