import { create, fromJsonString, toJsonString } from "@bufbuild/protobuf";

// Generated Protobuf schemas (from `experimental/novel/protos/*.proto`)
// NOTE: `src/gen` is generated by `npm run proto:gen`.
import type { ProjectRootInfo, SidecarEvent } from "@/gen/novel_sidecar_pb";
import {
  ListDirectoryRequestSchema,
  ListDirectoryResponseSchema,
  ProjectRootInfoSchema,
  ReadTextFileRequestSchema,
  ReadTextFileResponseSchema,
  SetProjectRootRequestSchema,
  SetProjectRootResponseSchema,
  SidecarEventSchema,
  WriteTextFileRequestSchema,
  WriteTextFileResponseSchema,
} from "@/gen/novel_sidecar_pb";

import { TextFormat, TextPayloadSchema } from "@/gen/novel_assets_pb";

// ============================================================
//  Sidecar Client (HTTP + SSE, Protobuf JSON)
//
//  Contract:
//  - GET  /api/novel/project-root -> ProjectRootInfo (protobuf json)
//  - POST /api/novel/project-root -> SetProjectRootRequest/Response (protobuf json)
//  - GET  /api/novel/events       -> SSE stream of SidecarEvent (protobuf json)
//  - POST /api/novel/fs/list      -> ListDirectoryRequest/Response (protobuf json)
//  - POST /api/novel/fs/read      -> ReadTextFileRequest/Response (protobuf json)
//  - POST /api/novel/fs/write     -> WriteTextFileRequest/Response (protobuf json)
// ============================================================

export type SidecarConnectionState = "idle" | "connecting" | "connected" | "error";

export function defaultSidecarUrl(): string {
  const env = (import.meta as any).env?.VITE_NOVEL_SIDECAR_URL as string | undefined;
  return env?.trim() ? env.trim() : "http://localhost:5678";
}

export function normalizeBaseUrl(baseUrl: string): string {
  let s = (baseUrl ?? "").trim();
  if (!s) return defaultSidecarUrl();
  // Port policy: 5000 is forbidden in this repo. Migrate legacy persisted values.
  s = s.replace(/:5000\b/g, ":5678");
  // Prefer `localhost` for loopback to avoid IPv4/IPv6 quirks across environments.
  s = s.replace(/:\/\/127\.0\.0\.1\b/g, "://localhost");
  s = s.replace(/\/+$/g, "");
  return s;
}

export async function getProjectRootInfo(baseUrl: string, ct?: AbortSignal): Promise<ProjectRootInfo> {
  const url = `${normalizeBaseUrl(baseUrl)}/api/novel/project-root`;
  const res = await fetch(url, { signal: ct });
  if (!res.ok) {
    throw new Error(`GET ${url} failed: ${res.status} ${res.statusText}`);
  }
  const json = await res.text();
  return fromJsonString(ProjectRootInfoSchema, json);
}

export async function setProjectRoot(baseUrl: string, projectRoot: string): Promise<ProjectRootInfo> {
  const url = `${normalizeBaseUrl(baseUrl)}/api/novel/project-root`;
  const req = create(SetProjectRootRequestSchema, { projectRoot });
  const body = toJsonString(SetProjectRootRequestSchema, req);

  const res = await fetch(url, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body,
  });

  if (!res.ok) {
    throw new Error(`POST ${url} failed: ${res.status} ${res.statusText}`);
  }

  const json = await res.text();
  const msg = fromJsonString(SetProjectRootResponseSchema, json) as any;
  // proto3 message field may be omitted in JSON; keep it defensive.
  if (!msg?.info) {
    return create(ProjectRootInfoSchema);
  }
  return msg.info as ProjectRootInfo;
}

export async function listDirectory(args: {
  baseUrl: string;
  relativePath: string;
  includeDirectories?: boolean;
  includeFiles?: boolean;
  onlySupportedTextFiles?: boolean;
  ct?: AbortSignal;
}) {
  const url = `${normalizeBaseUrl(args.baseUrl)}/api/novel/fs/list`;
  const req = create(ListDirectoryRequestSchema, {
    relativePath: args.relativePath ?? "",
    includeDirectories: args.includeDirectories ?? true,
    includeFiles: args.includeFiles ?? true,
    onlySupportedTextFiles: args.onlySupportedTextFiles ?? true,
  });
  const body = toJsonString(ListDirectoryRequestSchema, req);

  const res = await fetch(url, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body,
    signal: args.ct,
  });

  if (!res.ok) {
    throw new Error(`POST ${url} failed: ${res.status} ${res.statusText}`);
  }

  const json = await res.text();
  return fromJsonString(ListDirectoryResponseSchema, json);
}

export async function readTextFile(args: {
  baseUrl: string;
  relativePath: string;
  maxInlineBytes?: number;
  ct?: AbortSignal;
}): Promise<{ text: string; format: "markdown" | "plaintext" }> {
  const url = `${normalizeBaseUrl(args.baseUrl)}/api/novel/fs/read`;
  const req = create(ReadTextFileRequestSchema, {
    relativePath: args.relativePath ?? "",
    maxInlineBytes: args.maxInlineBytes ?? 4_000_000,
  });
  const body = toJsonString(ReadTextFileRequestSchema, req);

  const res = await fetch(url, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body,
    signal: args.ct,
  });

  if (!res.ok) {
    throw new Error(`POST ${url} failed: ${res.status} ${res.statusText}`);
  }

  const json = await res.text();
  const msg: any = fromJsonString(ReadTextFileResponseSchema, json);

  const content = msg?.content;
  const fmt = Number(content?.format ?? 0);
  const format: "markdown" | "plaintext" = fmt === Number(TextFormat.MARKDOWN) ? "markdown" : "plaintext";

  const oneof = content?.value;
  if (oneof?.case === "inlineText") {
    return { text: String(oneof.value ?? ""), format };
  }

  // Large file path: keep UI usable with preview.
  const preview = String(content?.preview ?? "");
  if (preview) return { text: preview, format };

  // If nothing is present, be defensive.
  return { text: "", format };
}

export async function writeTextFile(args: {
  baseUrl: string;
  relativePath: string;
  content: string;
  expectedContentHash?: string;
  ct?: AbortSignal;
}): Promise<{ success: boolean; message: string; contentHash?: string }> {
  const url = `${normalizeBaseUrl(args.baseUrl)}/api/novel/fs/write`;
  const lower = String(args.relativePath ?? "").toLowerCase();
  const format = lower.endsWith(".md") ? TextFormat.MARKDOWN : TextFormat.PLAIN_TEXT;

  const payload = create(TextPayloadSchema, {
    format,
    value: { case: "inlineText", value: args.content ?? "" },
    preview: "",
  });

  const req = create(WriteTextFileRequestSchema, {
    relativePath: args.relativePath ?? "",
    content: payload,
    expectedContentHash: args.expectedContentHash ?? "",
  });
  const body = toJsonString(WriteTextFileRequestSchema, req);

  const res = await fetch(url, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body,
    signal: args.ct,
  });

  if (!res.ok) {
    throw new Error(`POST ${url} failed: ${res.status} ${res.statusText}`);
  }

  const json = await res.text();
  const msg: any = fromJsonString(WriteTextFileResponseSchema, json);
  return {
    success: Boolean(msg?.success),
    message: String(msg?.message ?? ""),
    contentHash: typeof msg?.contentHash === "string" ? msg.contentHash : undefined,
  };
}

export async function smartContinue(args: {
  baseUrl: string;
  targetRelativePath: string;
  draftText?: string;
  instruction?: string;
  maxOutputChars?: number;
  maxContextChars?: number;
  includeObjects?: boolean;
  includeRoles?: boolean;
  includeRules?: boolean;
  ct?: AbortSignal;
}): Promise<{ success: boolean; message: string; generatedText: string; model?: string }> {
  const url = `${normalizeBaseUrl(args.baseUrl)}/api/novel/ai/continue`;

  // NOTE: Payload is Protobuf JSON (SmartContinueRequest), but we keep it schema-free here
  // to avoid coupling UI build to regenerated `src/gen` code.
  const payload = {
    targetRelativePath: args.targetRelativePath ?? "",
    draftText: args.draftText ?? "",
    instruction: args.instruction ?? "",
    maxOutputChars: args.maxOutputChars ?? 500,
    maxContextChars: args.maxContextChars ?? 60000,
    includeObjects: args.includeObjects ?? true,
    includeRoles: args.includeRoles ?? true,
    includeRules: args.includeRules ?? true,
  };

  const res = await fetch(url, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(payload),
    signal: args.ct,
  });

  if (!res.ok) {
    throw new Error(`POST ${url} failed: ${res.status} ${res.statusText}`);
  }

  const json: any = await res.json();
  return {
    success: Boolean(json?.success),
    message: String(json?.message ?? ""),
    generatedText: String(json?.generatedText ?? ""),
    model: typeof json?.model === "string" ? json.model : undefined,
  };
}

export function connectSidecarEvents(args: {
  baseUrl: string;
  onEvent: (evt: SidecarEvent) => void;
  onState?: (state: SidecarConnectionState, error?: string) => void;
}): () => void {
  const baseUrl = normalizeBaseUrl(args.baseUrl);
  const url = `${baseUrl}/api/novel/events`;

  let disposed = false;
  let es: EventSource | null = null;
  let retryTimer: any = null;
  let attempt = 0;

  const onOpen = () => {
    attempt = 0;
    args.onState?.("connected");
  };

  const onError = () => {
    if (disposed) return;

    // EventSource may auto-retry, but we explicitly recreate it for more predictable recovery.
    attempt = Math.min(attempt + 1, 10);
    args.onState?.("connecting", `SSE reconnecting (attempt ${attempt}): ${url}`);

    try {
      es?.close();
    } catch {
      // ignore
    }
    es = null;

    const delayMs = Math.min(250 * Math.pow(2, attempt), 8000);
    clearTimeout(retryTimer);
    retryTimer = setTimeout(connect, delayMs);
  };

  const onEvt = (e: MessageEvent) => {
    try {
      const evt = fromJsonString(SidecarEventSchema, String(e.data));
      args.onEvent(evt);
    } catch (err: any) {
      args.onState?.("error", `SSE decode failed: ${err?.message ?? String(err)}`);
    }
  };

  const attach = (source: EventSource) => {
    source.addEventListener("open", onOpen as any);
    source.addEventListener("error", onError as any);
    source.addEventListener("sidecar_event", onEvt as any);
  };

  const detach = (source: EventSource) => {
    source.removeEventListener("open", onOpen as any);
    source.removeEventListener("error", onError as any);
    source.removeEventListener("sidecar_event", onEvt as any);
  };

  const connect = () => {
    if (disposed) return;
    args.onState?.("connecting");

    const source = new EventSource(url);
    es = source;
    attach(source);
  };

  connect();

  return () => {
    disposed = true;
    clearTimeout(retryTimer);
    if (es) {
      detach(es);
      es.close();
    }
  };
}


