using System.Text.Json.Serialization;

namespace Aevatar.Agents.Knowledge.Graph.Models;

/// <summary>
/// Type of edge relationship in the knowledge graph.
/// Each edge type has specific semantics for node relationships.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum EdgeType
{
    /// <summary>
    /// Plan → Plan: Completing step N enables step N+1.
    /// </summary>
    PlanDependsOnPlan = 0,

    /// <summary>
    /// Knowledge → Knowledge: Knowledge derived from other knowledge through inference.
    /// </summary>
    KnowledgeDependsOnKnowledge = 1,

    /// <summary>
    /// Knowledge → Plan: Knowledge was generated by executing a plan step.
    /// </summary>
    KnowledgeMotivatedByPlan = 2,

    /// <summary>
    /// Plan → Knowledge/Goal: Plan step promotes achieving a goal or producing knowledge.
    /// </summary>
    PlanPromotesGoal = 3,

    /// <summary>
    /// Cross-session reference: Knowledge references knowledge from another session.
    /// </summary>
    CrossSessionReference = 4
}

/// <summary>
/// Base interface for all graph edges.
/// Each edge represents a directed relationship between two nodes.
/// </summary>
public interface IGraphEdge
{
    /// <summary>
    /// Source node ID.
    /// </summary>
    string FromId { get; }

    /// <summary>
    /// Target node ID.
    /// </summary>
    string ToId { get; }

    /// <summary>
    /// Type of this edge relationship.
    /// </summary>
    EdgeType Type { get; }

    /// <summary>
    /// When this edge was created.
    /// </summary>
    DateTimeOffset CreatedAt { get; }

    /// <summary>
    /// Session this edge belongs to.
    /// </summary>
    string SessionId { get; }

    /// <summary>
    /// Generates a human-readable explanation of this edge relationship.
    /// </summary>
    string Explain();
}

/// <summary>
/// Edge representing plan-to-plan dependency (execution order).
/// </summary>
public sealed class PlanDependencyEdge : IGraphEdge
{
    public required string FromId { get; init; }
    public required string ToId { get; init; }
    public EdgeType Type => EdgeType.PlanDependsOnPlan;
    public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow;
    public required string SessionId { get; init; }

    public string Explain() =>
        $"Plan '{FromId}' depends on completion of plan '{ToId}'";
}

/// <summary>
/// Edge representing knowledge-to-knowledge dependency (inference relationship).
/// </summary>
public sealed class KnowledgeDependencyEdge : IGraphEdge
{
    public required string FromId { get; init; }
    public required string ToId { get; init; }
    public EdgeType Type => EdgeType.KnowledgeDependsOnKnowledge;
    public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow;
    public required string SessionId { get; init; }

    public string Explain() =>
        $"Knowledge '{FromId}' is derived from knowledge '{ToId}'";
}

/// <summary>
/// Edge representing knowledge motivated by plan execution.
/// </summary>
public sealed class KnowledgeDerivationEdge : IGraphEdge
{
    public required string FromId { get; init; }
    public required string ToId { get; init; }
    public EdgeType Type => EdgeType.KnowledgeMotivatedByPlan;
    public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow;
    public required string SessionId { get; init; }

    public string Explain() =>
        $"Knowledge '{FromId}' was produced by executing plan '{ToId}'";
}

/// <summary>
/// Edge representing plan promoting a goal or knowledge.
/// </summary>
public sealed class PlanPromotesEdge : IGraphEdge
{
    public required string FromId { get; init; }
    public required string ToId { get; init; }
    public EdgeType Type => EdgeType.PlanPromotesGoal;
    public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow;
    public required string SessionId { get; init; }

    public string Explain() =>
        $"Plan '{FromId}' promotes achieving '{ToId}'";
}

/// <summary>
/// Edge representing cross-session knowledge reference.
/// </summary>
public sealed class CrossSessionReferenceEdge : IGraphEdge
{
    public required string FromId { get; init; }
    public required string ToId { get; init; }
    public EdgeType Type => EdgeType.CrossSessionReference;
    public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow;
    public required string SessionId { get; init; }

    /// <summary>
    /// The session ID of the referenced node (ToId contains the full global ID).
    /// </summary>
    public required string ReferencedSessionId { get; init; }

    public string Explain() =>
        $"Knowledge '{FromId}' references cross-session knowledge '{ToId}' from session '{ReferencedSessionId}'";
}

/// <summary>
/// Factory methods for creating edges.
/// </summary>
public static class GraphEdgeFactory
{
    /// <summary>
    /// Creates an edge based on the relationship between two nodes.
    /// </summary>
    public static IGraphEdge Create(
        string sessionId,
        string fromId,
        string toId,
        EdgeType type,
        string? referencedSessionId = null)
    {
        return type switch
        {
            EdgeType.PlanDependsOnPlan => new PlanDependencyEdge
            {
                SessionId = sessionId,
                FromId = fromId,
                ToId = toId
            },
            EdgeType.KnowledgeDependsOnKnowledge => new KnowledgeDependencyEdge
            {
                SessionId = sessionId,
                FromId = fromId,
                ToId = toId
            },
            EdgeType.KnowledgeMotivatedByPlan => new KnowledgeDerivationEdge
            {
                SessionId = sessionId,
                FromId = fromId,
                ToId = toId
            },
            EdgeType.PlanPromotesGoal => new PlanPromotesEdge
            {
                SessionId = sessionId,
                FromId = fromId,
                ToId = toId
            },
            EdgeType.CrossSessionReference => new CrossSessionReferenceEdge
            {
                SessionId = sessionId,
                FromId = fromId,
                ToId = toId,
                ReferencedSessionId = referencedSessionId ?? ExtractSessionId(toId)
            },
            _ => throw new ArgumentOutOfRangeException(nameof(type), type, "Unknown edge type")
        };
    }

    /// <summary>
    /// Extracts session ID from a global node ID (format: sessionId:nodeId).
    /// </summary>
    private static string ExtractSessionId(string globalNodeId)
    {
        var parts = globalNodeId.Split(':', 2);
        return parts.Length == 2 ? parts[0] : string.Empty;
    }
}
