using System.Text.Json.Serialization;

namespace Aevatar.Agents.Knowledge.Graph.Models;

/// <summary>
/// DEPRECATED: Legacy relationship type enum.
/// Use EdgeType instead for new code.
/// </summary>
[Obsolete("Use EdgeType instead. This enum will be removed in a future version.")]
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum RelationshipType
{
    /// <summary>PlanNode to PlanNode: Completing step N enables step N+1.</summary>
    Promotes = 0,

    /// <summary>KnowledgeNode to KnowledgeNode: Knowledge derived from other knowledge.</summary>
    DependsOn = 1,

    /// <summary>KnowledgeNode to PlanNode: Knowledge was generated by executing a plan step.</summary>
    MotivatedBy = 2
}

/// <summary>
/// A directed edge in the knowledge graph.
/// Implements IGraphEdge for compatibility with the new edge system.
/// </summary>
public sealed class KnowledgeEdge : IGraphEdge
{
    /// <summary>Source node ID.</summary>
    public required string FromId { get; init; }

    /// <summary>Target node ID.</summary>
    public required string ToId { get; init; }

    /// <summary>
    /// DEPRECATED: Use Type property instead.
    /// Legacy relationship type for backward compatibility.
    /// </summary>
    [Obsolete("Use Type property instead.")]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public RelationshipType RelationshipType { get; init; } = RelationshipType.DependsOn;

    /// <summary>When this edge was created.</summary>
    public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>Session this edge belongs to.</summary>
    public string SessionId { get; init; } = "";

    /// <summary>Edge type derived from legacy RelationshipType.</summary>
    public EdgeType Type => MapRelationshipTypeToEdgeType(RelationshipType);

    /// <inheritdoc />
    public string Explain()
    {
        return Type switch
        {
            EdgeType.PlanDependsOnPlan => $"Plan '{FromId}' depends on plan '{ToId}'",
            EdgeType.KnowledgeDependsOnKnowledge => $"Knowledge '{FromId}' is derived from '{ToId}'",
            EdgeType.KnowledgeMotivatedByPlan => $"Knowledge '{FromId}' was produced by plan '{ToId}'",
            EdgeType.PlanPromotesGoal => $"Plan '{FromId}' promotes '{ToId}'",
            _ => $"Edge from '{FromId}' to '{ToId}'"
        };
    }

    /// <summary>
    /// Maps legacy RelationshipType to new EdgeType.
    /// </summary>
    private static EdgeType MapRelationshipTypeToEdgeType(RelationshipType rt)
    {
        return rt switch
        {
            RelationshipType.Promotes => EdgeType.PlanPromotesGoal,
            RelationshipType.DependsOn => EdgeType.KnowledgeDependsOnKnowledge,
            RelationshipType.MotivatedBy => EdgeType.KnowledgeMotivatedByPlan,
            _ => EdgeType.KnowledgeDependsOnKnowledge
        };
    }

    /// <summary>
    /// Creates a KnowledgeEdge from an IGraphEdge.
    /// </summary>
    public static KnowledgeEdge FromGraphEdge(IGraphEdge edge)
    {
        return new KnowledgeEdge
        {
            FromId = edge.FromId,
            ToId = edge.ToId,
            SessionId = edge.SessionId,
            CreatedAt = edge.CreatedAt,
            RelationshipType = MapEdgeTypeToRelationshipType(edge.Type)
        };
    }

    private static RelationshipType MapEdgeTypeToRelationshipType(EdgeType et)
    {
        return et switch
        {
            EdgeType.PlanDependsOnPlan => RelationshipType.Promotes,
            EdgeType.PlanPromotesGoal => RelationshipType.Promotes,
            EdgeType.KnowledgeDependsOnKnowledge => RelationshipType.DependsOn,
            EdgeType.KnowledgeMotivatedByPlan => RelationshipType.MotivatedBy,
            _ => RelationshipType.DependsOn
        };
    }
}
