using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using Aevatar.Agents.Abstractions;
using Aevatar.Agents.Abstractions.Attributes;
using Aevatar.Agents.Abstractions.Helpers;
using Aevatar.Agents.Abstractions.Memory;
using Aevatar.Agents.AI;
using Aevatar.Agents.AI.Abstractions;
using Aevatar.Agents.AI.Core.Hooks;
using Aevatar.Agents.AI.Core.Messages;
using Aevatar.Agents.AI.Core.Utils;
using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;
using Microsoft.Extensions.Logging;

// ReSharper disable InconsistentNaming
namespace Aevatar.Agents.AI.Core;

public abstract partial class AIGAgentBase
{
    // Baseline tool allowlist applied to every LLM request.

    private HashSet<string>? _fixedToolAllowlist;
    private LlmRequestRuntime? _llmRequestRuntime;
    private LlmRequestRuntime LlmRequest => _llmRequestRuntime ??= new LlmRequestRuntime(this);

    private AIGAgentChatRuntime? _chatRuntime;
    private AIGAgentChatRuntime ChatRuntime => _chatRuntime ??= new AIGAgentChatRuntime(this);

    private static readonly MethodInfo ChatRequestHandlerMethod =
        typeof(AIGAgentBase).GetMethod(nameof(HandleChatRequestEvent),
            BindingFlags.Instance | BindingFlags.NonPublic)!;

    private bool HasCustomChatRequestHandler()
    {
        var handlers = GetEventHandlers();
        foreach (var handler in handlers)
        {
            if (handler.IsAllEventHandler)
                continue;
            if (handler.ParameterType != typeof(ChatRequestEvent))
                continue;
            if (!Equals(handler.Method, ChatRequestHandlerMethod))
                return true;
        }

        return false;
    }

    [EventHandler(AllowSelfHandling = true)]
    protected virtual async Task HandleChatRequestEvent(ChatRequestEvent evt)
    {
        if (evt == null)
            return;

        // If a derived class provides its own ChatRequestEvent handler, skip the base handler to avoid duplicates.
        if (HasCustomChatRequestHandler())
            return;

        var requestId = string.IsNullOrWhiteSpace(evt.RequestId)
            ? Guid.NewGuid().ToString("N")
            : evt.RequestId;

        var request = new ChatRequest
        {
            RequestId = requestId,
            Message = evt.Message ?? string.Empty
        };

        if (!string.IsNullOrWhiteSpace(evt.UserId))
        {
            request.Context["user_id"] = evt.UserId.Trim();
        }

        if (evt.Context != null)
        {
            foreach (var (key, value) in evt.Context)
            {
                if (!string.IsNullOrWhiteSpace(key))
                {
                    request.Context[key] = value ?? string.Empty;
                }
            }
        }

        if (evt.MaxTokens > 0)
        {
            request.MaxTokens = evt.MaxTokens;
        }

        if (evt.Temperature > 0)
        {
            request.Temperature = evt.Temperature;
        }

        const int DefaultStreamChunkEveryN = 8;
        var chunkEvery = evt.StreamChunkEveryN > 0 ? evt.StreamChunkEveryN : DefaultStreamChunkEveryN;
        chunkEvery = Math.Clamp(chunkEvery, 1, 128);

        var buffer = new StringBuilder();
        var pending = new StringBuilder();
        var rawChunkCount = 0;
        var publishedIndex = 0;

        await foreach (var chunk in ChatStreamAsync(request, CancellationToken.None))
        {
            if (string.IsNullOrEmpty(chunk))
                continue;

            buffer.Append(chunk);
            pending.Append(chunk);
            rawChunkCount++;

            if (rawChunkCount % chunkEvery != 0)
                continue;

            publishedIndex++;
            await PublishAsync(new ChatStreamChunkEvent
            {
                RequestId = requestId,
                Content = pending.ToString(),
                ChunkIndex = publishedIndex,
                Timestamp = Timestamp.FromDateTime(DateTime.UtcNow)
            });
            pending.Clear();
        }

        if (pending.Length > 0)
        {
            publishedIndex++;
            await PublishAsync(new ChatStreamChunkEvent
            {
                RequestId = requestId,
                Content = pending.ToString(),
                ChunkIndex = publishedIndex,
                Timestamp = Timestamp.FromDateTime(DateTime.UtcNow)
            });
        }

        await PublishAsync(new ChatResponseEvent
        {
            RequestId = requestId,
            Content = buffer.ToString(),
            Timestamp = Timestamp.FromDateTime(DateTime.UtcNow)
        });
    }


    /// <summary>
    /// Set a fixed baseline tool allowlist for all LLM requests generated by this agent.
    /// Passing null/empty will clear the baseline allowlist (fallback to default behavior).
    /// </summary>
    public void SetFixedToolAllowlist(IEnumerable<string>? toolNames)
    {
        if (toolNames == null)
        {
            _fixedToolAllowlist = null;
            return;
        }

        var list = toolNames
            .Select(x => (x ?? string.Empty).Trim())
            .Where(x => x.Length > 0)
            .ToList();

        _fixedToolAllowlist = list.Count == 0
            ? null
            : new HashSet<string>(list, StringComparer.OrdinalIgnoreCase);
    }

    public enum StreamingToolCallMode
    {
        EmitFinalAnswerAsSingleChunk = 0,
        ContinueStreamingAfterTools = 1
    }

    protected virtual StreamingToolCallMode StreamingToolCalls => StreamingToolCallMode.EmitFinalAnswerAsSingleChunk;

    protected virtual void LogChatStreamTokenReadException(Exception exception, ChatRequest request)
    {
        Logger.LogError(exception, "Error in streaming chat request {RequestId}", request.RequestId);
    }

    public virtual async Task<ChatResponse> ChatAsync(
        ChatRequest request,
        CancellationToken cancellationToken = default)
    {
        return await ChatRuntime.ChatAsync(request, cancellationToken);
    }

    protected virtual AevatarLLMRequest BuildLLMRequest(
        ChatRequest request)
    {
        return LlmRequest.BuildRequest(request);
    }

    protected virtual string? GetEffectiveSystemPrompt()
    {
        return !string.IsNullOrWhiteSpace(Config.SystemPrompt)
            ? Config.SystemPrompt
            : SystemPrompt;
    }

    /// <summary>
    /// Get LLM settings from chat request.
    /// </summary>
    protected virtual AevatarLLMSettings GetLLMSettings(ChatRequest request)
    {
        // Use request values if provided (considering 0 as a valid temperature), otherwise use configuration
        // For temperature: accept any value >= 0 as valid override
        // For maxTokens: only positive values are valid overrides
        var temperature = request.Temperature >= 0 ? request.Temperature : Config.Temperature;
        var maxTokens = request.MaxTokens > 0 ? request.MaxTokens : Config.MaxOutputTokens;

        return new AevatarLLMSettings
        {
            Temperature = temperature,
            MaxTokens = maxTokens,
            ModelId = Config.Model
        };
    }

    /// <summary>
    /// Create a chat request with the given message.
    /// </summary>
    public virtual ChatRequest CreateChatRequest(string message)
    {
        return ChatRequest.Create(message);
    }

    /// <summary>
    /// Generate a response to a message (convenience method).
    /// </summary>
    public virtual Task<ChatResponse> GenerateResponseAsync(
        string message,
        CancellationToken cancellationToken = default)
    {
        var request = CreateChatRequest(message);
        return ChatAsync(request, cancellationToken);
    }

    /// <summary>
    /// Generate a streaming response to a chat request.
    /// </summary>
    public virtual IAsyncEnumerable<string> ChatStreamAsync(
        ChatRequest request,
        CancellationToken cancellationToken = default)
        => ChatRuntime.ChatStreamAsync(request, cancellationToken);

    private async Task<AevatarLLMRequest> PrepareChatStreamAsync(ChatRequest request, CancellationToken cancellationToken)
    {
        // Keep history bounded before building request (prevents token blow-up).
        await CompactChatHistoryIfNeededAsync(cancellationToken);

        // Ensure built-in tools are registered and cached.
        await InitializeToolsAsync(cancellationToken);

        // Best-effort MCP retry (throttled) before building request so tools can be visible to LLM.
        await TryReconnectMcpOnChatAsync(cancellationToken);

        // Build LLM request
        var llmRequest = BuildLLMRequest(request);

        // Optional: persist the user message (default off)
        if (EnableChatHistoryInState)
        {
            AddMessageToHistory(request.Message, AevatarChatRole.User);
        }

        // Optional: persist conversation to MemoryStore (default off, best-effort)
        await AppendChatMemoryAsync(AevatarChatRole.User, request.Message ?? string.Empty, request, cancellationToken);

        return llmRequest;
    }

    private async Task<AevatarLLMToken?> TryReadNextStreamingTokenAsync(
        IAsyncEnumerator<AevatarLLMToken> enumerator,
        ChatRequest request,
        CancellationToken cancellationToken)
    {
        try
        {
            var hasNext = await enumerator.MoveNextAsync();
            return hasNext ? enumerator.Current : null;
        }
        catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
        {
            // Normal: streaming request canceled by caller (e.g., client disconnected).
            throw;
        }
        catch (Exception ex)
        {
            LogChatStreamTokenReadException(ex, request);
            throw;
        }
    }

    private async Task<string> ExecuteToolCallFromStreamingTokenAsync(
        ChatRequest request,
        AevatarLLMRequest llmRequest,
        AevatarLLMToken token,
        StringBuilder? assistantBuffer,
        StringBuilder? reasoningBuffer,
        CancellationToken cancellationToken)
    {
        var toolCallResponse = new AevatarLLMResponse
        {
            AevatarFunctionCall = token.AevatarFunctionCall,
            // Capture any reasoning accumulated so far for the history/logging if needed
            Content = assistantBuffer?.ToString() ?? string.Empty
        };

        var accumulatedReasoning = reasoningBuffer?.ToString();
        if (!string.IsNullOrEmpty(accumulatedReasoning))
        {
            toolCallResponse.Metadata ??= new Dictionary<string, object>();
            toolCallResponse.Metadata["reasoning_content"] = accumulatedReasoning;
        }

        var (finalResponse, _) = await ExecuteToolCallLoopAsync(
            request,
            llmRequest,
            toolCallResponse,
            cancellationToken);

        return finalResponse.Content ?? string.Empty;
    }

    private async Task PersistStreamingAssistantOutputAsync(
        ChatRequest request,
        StringBuilder? assistantBuffer,
        StringBuilder? reasoningBuffer,
        bool completedSuccessfully,
        CancellationToken cancellationToken)
    {
        if (!completedSuccessfully)
            return;

        var assistantText = assistantBuffer?.ToString() ?? string.Empty;
        var finalReasoning = reasoningBuffer?.ToString();

        // Persist assistant message only if stream completed successfully
        if (EnableChatHistoryInState)
        {
            if (!string.IsNullOrEmpty(assistantText) || !string.IsNullOrEmpty(finalReasoning))
            {
                var msg = new AevatarChatMessage
                {
                    Role = AevatarChatRole.Assistant,
                    Content = assistantText,
                    Timestamp = TimestampHelper.GetUtcNow()
                };

                if (!string.IsNullOrEmpty(finalReasoning))
                {
                    msg.Metadata.Add("reasoning_content", finalReasoning);
                }

                AddMessageToHistory(msg);
            }
        }

        // Optional: persist assistant output to MemoryStore (default off, best-effort)
        if (!string.IsNullOrWhiteSpace(assistantText))
        {
            await AppendChatMemoryAsync(AevatarChatRole.Assistant, assistantText, request, cancellationToken);
        }
    }

    /// <summary>
    /// Generate a streaming response to a message (convenience method).
    /// </summary>
    public virtual IAsyncEnumerable<string> GenerateResponseStreamAsync(
        string message,
        CancellationToken cancellationToken = default)
    {
        var request = CreateChatRequest(message);
        return ChatStreamAsync(request, cancellationToken);
    }

    /// <summary>
    /// Check if the LLM provider supports streaming.
    /// </summary>
    public virtual async Task<bool> SupportsStreamingAsync(CancellationToken cancellationToken = default)
    {
        if (!_isInitialized)
            return false;

        if (ActiveProviderConfig?.EnableStreaming == false)
            return false;

        if (ActiveProviderConfig?.EnableStreaming == true)
            return true;

        var modelInfo = await LLMProvider.GetModelInfoAsync(cancellationToken);
        return modelInfo.SupportsStreaming;
    }

    // Streaming sink registry (DI injected, best-effort).
    internal IStreamChunkSinkRegistry? StreamChunkSinkRegistry { get; set; }

    private HistoryRuntime? _historyRuntime;
    private HistoryRuntime History => _historyRuntime ??= new HistoryRuntime(this);

    public bool EnableChatHistoryInState { get; set; }
    public bool EnableChatHistoryCompaction { get; set; }
    public int ChatHistoryMaxMessages { get; set; } = 40;
    public int ChatHistorySummaryMaxChars { get; set; } = 4000;

    protected virtual void AddMessageToHistory(string content, AevatarChatRole role, string? name = null)
        => History.AddMessage(content, role, name);

    protected virtual void AddMessageToHistory(AevatarChatMessage message)
        => History.AddMessage(message);

    protected virtual Task CompactChatHistoryIfNeededAsync(CancellationToken cancellationToken = default)
        => History.CompactIfNeededAsync(cancellationToken);

    private string BuildEffectiveSystemPromptWithSummary()
    {
        var basePrompt = GetEffectiveSystemPrompt() ?? string.Empty;

        var toolBlock = BuildToolInstructionBlock();
        var mergedPrompt = string.IsNullOrWhiteSpace(toolBlock)
            ? basePrompt
            : string.IsNullOrWhiteSpace(basePrompt)
                ? toolBlock
                : $"{basePrompt}\n\n{toolBlock}";

        return History.AppendSummaryToSystemPrompt(mergedPrompt);
    }

    protected virtual IReadOnlyList<AevatarChatMessage> SnapshotChatHistoryMessages()
        => History.SnapshotHistoryMessages();

    protected IMemoryStore? MemoryStore { get; set; }
    protected IMemoryVectorIndex? MemoryVectorIndex { get; set; }

    public bool EnableMemoryStoreAppend { get; set; }
    public bool EnableSessionMemoryStoreAppend { get; set; }
    public bool EnableMemoryVectorIndexAppend { get; set; }

    public MemoryScopeType MemoryStoreScopeType { get; set; } = MemoryScopeType.PrivateAgent;
    public string? MemoryStoreScopeIdOverride { get; set; }
    public string? MemoryIdOverride { get; set; }

    private MemoryStoreRuntime? _memoryStoreRuntime;
    private MemoryStoreRuntime MemoryRuntime => _memoryStoreRuntime ??= new MemoryStoreRuntime(this);

    protected virtual async Task AppendChatMemoryAsync(
        AevatarChatRole role,
        string content,
        ChatRequest request,
        CancellationToken ct)
    {
        await MemoryRuntime.AppendChatMemoryAsync(role, content, request, ct);
        await AppendSessionChatMemoryAsync(role, content, request, ct);
    }

    protected virtual Task AppendMemoryVectorAsync(MemoryEntry entry, CancellationToken ct)
        => MemoryRuntime.AppendMemoryVectorAsync(entry, ct);

    protected virtual MemoryScope BuildMemoryScope(ChatRequest request)
    {
        var type = MemoryStoreScopeType == MemoryScopeType.Unspecified
            ? MemoryScopeType.PrivateAgent
            : MemoryStoreScopeType;

        var scopeId = MemoryStoreScopeIdOverride;
        if (string.IsNullOrWhiteSpace(scopeId))
        {
            scopeId = type switch
            {
                MemoryScopeType.Session => TryGetContextValue(
                    request,
                    ChatRequest.SessionIdKey,
                    ChatRequest.SessionIdKeyCamel),
                MemoryScopeType.Run => TryGetContextValue(request, "run_id", "runId"),
                MemoryScopeType.Execution => TryGetContextValue(request, "execution_id", "executionId"),
                MemoryScopeType.Graph => TryGetContextValue(request, "graph_id", "graphId"),
                MemoryScopeType.Tenant => TryGetContextValue(request, "tenant_id", "tenantId"),
                _ => Id.ToString()
            };
        }

        scopeId = string.IsNullOrWhiteSpace(scopeId) ? Id.ToString() : scopeId.Trim();

        return new MemoryScope
        {
            Type = type,
            ScopeId = scopeId
        };
    }

    protected virtual string BuildMemoryId(MemoryScope scope)
    {
        if (!string.IsNullOrWhiteSpace(MemoryIdOverride))
            return MemoryIdOverride.Trim();

        var type = scope.Type.ToString().ToLowerInvariant();
        var id = (scope.ScopeId ?? string.Empty).Trim();
        return $"{type}::{id}";
    }

    protected virtual async Task AppendSessionChatMemoryAsync(
        AevatarChatRole role,
        string content,
        ChatRequest request,
        CancellationToken ct)
    {
        if (!EnableSessionMemoryStoreAppend)
            return;

        if (!TryGetSessionId(request, out var sessionId))
            return;

        var scope = BuildSessionMemoryScope(sessionId);
        var memoryId = BuildSessionMemoryId(sessionId);
        await MemoryRuntime.AppendChatMemoryOverrideAsync(role, content, request, scope, memoryId, ct);
    }

    protected virtual bool TryGetSessionId(ChatRequest request, out string sessionId)
    {
        sessionId = string.Empty;
        var value = TryGetContextValue(request, ChatRequest.SessionIdKey, ChatRequest.SessionIdKeyCamel);
        if (string.IsNullOrWhiteSpace(value))
            return false;

        sessionId = value.Trim();
        return sessionId.Length > 0;
    }

    protected virtual MemoryScope BuildSessionMemoryScope(string sessionId)
        => new() { Type = MemoryScopeType.Session, ScopeId = sessionId.Trim() };

    protected virtual string BuildSessionMemoryId(string sessionId)
        => $"{MemoryScopeType.Session.ToString().ToLowerInvariant()}::{(sessionId ?? string.Empty).Trim()}";

    private static string? TryGetContextValue(ChatRequest request, params string[] keys)
    {
        if (request?.Context == null || request.Context.Count == 0)
            return null;

        foreach (var k in keys)
        {
            if (string.IsNullOrWhiteSpace(k)) continue;
            if (!request.Context.TryGetValue(k, out var v)) continue;
            if (string.IsNullOrWhiteSpace(v)) continue;
            return v.Trim();
        }

        return null;
    }

    bool ILlmRequestHost.EnableChatHistoryInState => EnableChatHistoryInState;
    IReadOnlyCollection<string>? ILlmRequestHost.FixedToolAllowlist => _fixedToolAllowlist;
    AevatarLLMSettings ILlmRequestHost.GetLLMSettings(ChatRequest request) => GetLLMSettings(request);
    string ILlmRequestHost.BuildEffectiveSystemPromptWithSummary() => BuildEffectiveSystemPromptWithSummary();
    IReadOnlyList<AevatarChatMessage> ILlmRequestHost.SnapshotChatHistoryMessages() => SnapshotChatHistoryMessages();
    void ILlmRequestHost.AttachToolsToRequest(AevatarLLMRequest llmRequest) => AttachToolsToRequest(llmRequest);

    ILogger IAIGAgentChatRuntimeHost.Logger => Logger;
    string IAIGAgentChatRuntimeHost.AgentId => Id.ToString();
    bool IAIGAgentChatRuntimeHost.EnableChatHistoryInState => EnableChatHistoryInState;
    bool IAIGAgentChatRuntimeHost.AutoConfirmEvents => AutoConfirmEvents;
    object? IAIGAgentChatRuntimeHost.EventStore => EventStore;
    void IAIGAgentChatRuntimeHost.EnsureInitialized() => EnsureInitialized();

    Task IAIGAgentChatRuntimeHost.RunSessionStartHooksAsync(ChatRequest request, bool isStreaming, CancellationToken ct)
        => RunSessionStartHooksAsync(request, isStreaming, ct);

    Task IAIGAgentChatRuntimeHost.RunStopHooksAsync(
        ChatRequest request,
        bool isStreaming,
        AevatarAgentHookStopStatus status,
        TimeSpan duration,
        Exception? exception)
        => RunStopHooksAsync(request, isStreaming, status, duration, exception);

    Task IAIGAgentChatRuntimeHost.RunSessionEndHooksAsync(
        ChatRequest request,
        bool isStreaming,
        AevatarAgentHookStopStatus status,
        TimeSpan duration,
        Exception? exception)
        => RunSessionEndHooksAsync(request, isStreaming, status, duration, exception);

    Task IAIGAgentChatRuntimeHost.CompactChatHistoryIfNeededAsync(CancellationToken ct)
        => CompactChatHistoryIfNeededAsync(ct);

    Task IAIGAgentChatRuntimeHost.InitializeToolsAsync(CancellationToken ct) => InitializeToolsAsync(ct);
    Task IAIGAgentChatRuntimeHost.TryReconnectMcpOnChatAsync(CancellationToken ct) => TryReconnectMcpOnChatAsync(ct);

    AevatarLLMRequest IAIGAgentChatRuntimeHost.BuildLLMRequest(ChatRequest request) => BuildLLMRequest(request);

    Task<AevatarLLMResponse> IAIGAgentChatRuntimeHost.GenerateLLMWithHooksAsync(
        ChatRequest request,
        AevatarLLMRequest llmRequest,
        CancellationToken ct)
        => GenerateLLMWithHooksAsync(request, llmRequest, ct);

    IAsyncEnumerable<AevatarLLMToken> IAIGAgentChatRuntimeHost.GenerateLLMStreamWithHooksAsync(
        string requestId,
        AevatarLLMRequest llmRequest,
        CancellationToken ct)
        => GenerateLLMStreamWithHooksAsync(requestId, llmRequest, ct);

    Task<(AevatarLLMResponse FinalResponse, ToolCallInfo? ToolCall)> IAIGAgentChatRuntimeHost.ExecuteToolCallLoopAsync(
        ChatRequest request,
        AevatarLLMRequest llmRequest,
        AevatarLLMResponse initialResponse,
        CancellationToken ct)
        => ExecuteToolCallLoopAsync(request, llmRequest, initialResponse, ct);

    void IAIGAgentChatRuntimeHost.AddMessageToHistory(string content, AevatarChatRole role)
        => AddMessageToHistory(content, role);

    void IAIGAgentChatRuntimeHost.AddMessageToHistory(AevatarChatMessage message) => AddMessageToHistory(message);

    Task IAIGAgentChatRuntimeHost.AppendChatMemoryAsync(AevatarChatRole role, string content, ChatRequest request, CancellationToken ct)
        => AppendChatMemoryAsync(role, content, request, ct);

    Task IAIGAgentChatRuntimeHost.PublishAsync(IMessage message, EventDirection direction, CancellationToken ct)
        => PublishAsync((dynamic)message, direction, ct);

    (string Provider, string Model) IAIGAgentChatRuntimeHost.GetProviderAndModelForTelemetry()
        => GetProviderAndModelForTelemetry();

    void IAIGAgentChatRuntimeHost.RaiseAIDecision(string prompt, string response, int tokensUsed, Dictionary<string, string>? metadata)
        => RaiseAIDecision(prompt, response, tokensUsed, metadata);

    Task IAIGAgentChatRuntimeHost.ConfirmEventsAsync(CancellationToken ct) => ConfirmEventsAsync(ct);
    StreamingToolCallMode IAIGAgentChatRuntimeHost.GetStreamingToolCallMode() => StreamingToolCalls;
    void IAIGAgentChatRuntimeHost.LogChatStreamTokenReadException(Exception exception, ChatRequest request)
        => LogChatStreamTokenReadException(exception, request);
}